# Generated by Django 4.1.3 on 2023-04-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('tugilgan_yil', models.PositiveSmallIntegerField()),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('tel_raqam', models.CharField(max_length=20)),
                ('faol', models.BooleanField(default=True)),
                ('longlitude', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=30)),
            ],
        ),
    ]
